# -*- coding: utf-8 -*-
"""Basic tensor operations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GdJe4W7EbuiZtc2XHcOEopWdmmyuy__
"""

import tensorflow as tf

#Initialization of tensors
x = tf.constant(4)
print(x)

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

x = tf.constant([[1,2,3],[4,5,6]])
print(x)

x=tf.ones((3,3))
print(x)

x=tf.zeros((2,3))
print(x)

x=tf.eye(3)
print(x)

x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.range(10)

x =tf.range(start=1, limit=10, delta=2)
print(x)

x = tf.cast(x, dtype=tf.float32)
print(x)

"""Mathematical Operations"""

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y)
print(z)

z = tf.subtract(x,y)
print(z)

z = tf.multiply(x,y)
print(z)

z = tf.divide(x,y)
print(z)

z = tf.tensordot(x,y, axes=1)
print(z)

z = tf.reduce_sum(x*y, axis=0)
print(z)

z = x ** 5
print(z)

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y)
print(z)

"""Indexing

"""

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[1:])

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[1:3])

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[::2])

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[::-1])

indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0,:])

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0:2,:])

"""Reshaping"""

x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

x = tf.constant([[1,2,3,4,5,6]])
print(x.shape)

x = tf.constant([1,2,3,4,5,6])
print(x.shape)